# Generated by Django 4.2.5 on 2024-01-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('group_name', models.CharField(max_length=255)),
                ('person', models.CharField(max_length=255)),
                ('expenditure', models.FloatField()),
            ],
        ),
    ]
