# Generated by Django 4.2.5 on 2024-01-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transname', models.CharField(max_length=30)),
                ('amtspent', models.CharField(max_length=10)),
                ('personName', models.CharField(editable=False, max_length=255)),
                ('persons', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=25)),
            ],
        ),
    ]
