# Generated by Django 4.2.5 on 2024-01-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_addtransaction_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtransaction',
            name='personName',
            field=models.CharField(max_length=255),
        ),
    ]
