# Generated by Django 4.2.5 on 2024-01-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_addtransaction_personspent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddTransaction',
        ),
    ]
