# Generated by Django 4.2.5 on 2024-01-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_delete_addtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transname', models.CharField(max_length=30)),
                ('amtspent', models.CharField(max_length=10)),
                ('personName', models.CharField(max_length=255)),
                ('personspent', models.CharField(max_length=20)),
            ],
        ),
    ]
